name: CI

on:
  pull_request:

env:
  COVERAGE_DIR: "target/coverage"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.2
        with:
          lein: 2.9.8

      - name: Coverage report
        id: report-coverage
        run: |
          lein cloverage --no-colorize -o "${{ env.COVERAGE_DIR }}" > coverage-report.log

      - name: Diff coverage
        id: diff-coverage
        run: |
          cat coverage-report.log | sed -n '/Writing HTML report to/,$p' | sed '1,2d' > branch.log
          echo "\`\`\`diff" >> diff.log
          diff --suppress-common-lines --color='never' branch.log master.log >> diff.log
          echo "\`\`\`" >> diff.log
          cat diff.log

      - name: Comment coverage
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: diff.log
