name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  COVERAGE_DIR: "target/coverage"
  PR_COVERAGE_FILE: "coverage-report.log"
  PR_COVERAGE_SUMMARY_FILE: "branch-coverage.log"
  COVERAGE_DIFF_FILE: "diff.log"
  MAIN_COVERAGE_FILE: "main-coverage.log"

jobs:
  test:
    uses: blue0513/cloverage-action/.github/workflows/ci.yml@main
    secrets: inherit
