name: CI

on:
  workflow_call:
    inputs:
      uploaded-path:
        required: false
        type: string
        default: ''
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:

env:
  REGION: "ap-northeast-1"
  COVERAGE_DIR: "target/coverage"
  PR_COVERAGE_FILE: "coverage-report"
  MAIN_COVERAGE_FILE: "base-coverage-report"

jobs:
  coverage:
    runs-on: ubuntu-latest
    outputs:
      s3_url: ${{ steps.upload-s3.outputs.s3_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: DeLaGuardo/setup-clojure@10.2
        with:
          lein: 2.9.8
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: echo ${{ github.event_name }}

      - uses: actions/download-artifact@v3
        if: ${{ inputs.uploaded-path != '' }}
        with:
          name: ${{ inputs.uploaded-path }}
          path: "${{ env.COVERAGE_DIR }}"

      - name: Calculate coverage of this branch
        if: ${{ inputs.uploaded-path == '' }}
        run: |
          lein cloverage --lcov --no-colorize -o "${{ env.COVERAGE_DIR }}"

      - name: Upload html to S3
        id: upload-s3
        if: ${{ vars.S3_BUCKET_NAME != '' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          HTML_DIR: "report-output"
        run: |
          npm i @lcov-viewer/cli -g
          lcov-viewer lcov "${{ env.COVERAGE_DIR }}/lcov.info" -o "${{ env.HTML_DIR }}"
          aws s3 cp --region ${{ env.REGION }} --recursive "${{ env.HTML_DIR }}/" "s3://${{ vars.S3_BUCKET_NAME }}/${{ github.run_id }}/"
          S3_URL="https://${{ vars.S3_BUCKET_NAME }}.s3.${{ env.REGION }}.amazonaws.com/${{ github.run_id}}/index.html"
          echo "s3_url=${S3_URL}" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.PR_COVERAGE_FILE }}-${{ github.run_id }}"
          path: "${{ env.COVERAGE_DIR }}/lcov.info"

  coverage-diff:
    if: github.ref != 'refs/heads/main'
    needs: coverage
    runs-on: ubuntu-latest
    env:
      COVERAGE_DIFF_FILE: "coverate-diff.log"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: "${{ env.PR_COVERAGE_FILE }}-${{ github.run_id }}"
          path: "${{ env.COVERAGE_DIR }}"

      - name: Download main coverage artifact
        run: gh run download -n ${{ env.MAIN_COVERAGE_FILE }} || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check coverage file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "${{ env.MAIN_COVERAGE_FILE }}, ${{ env.COVERAGE_DIR }}/lcov.info"

      - name: Create coverage diff comment
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          [ -n "${{ needs.coverage.outputs.s3_url }}" ] && URL="[Full Coverage Report](${{ needs.coverage.outputs.s3_url }})"
          SUMMARY_TABLE=$(docker run --rm -v ${PWD}:/lcov-compare/lcovs ghcr.io/blue0513/cloverage-action-lcov-compare:main -b lcovs/${{ env.MAIN_COVERAGE_FILE }} -t lcovs/${{ env.COVERAGE_DIR }}/lcov.info -o table -c line --icon --onlySummary)
          DETAIL_TABLE=$( docker run --rm -v ${PWD}:/lcov-compare/lcovs ghcr.io/blue0513/cloverage-action-lcov-compare:main -b lcovs/${{ env.MAIN_COVERAGE_FILE }} -t lcovs/${{ env.COVERAGE_DIR }}/lcov.info -o table -c line --icon)

          echo "## Coverage Report"                         > ${{ env.COVERAGE_DIFF_FILE }}
          echo "${URL}"                                    >> ${{ env.COVERAGE_DIFF_FILE }}
          echo ${SUMMARY_TABLE}                            >> ${{ env.COVERAGE_DIFF_FILE }}
          echo "<details><summary>report detail</summary>" >> ${{ env.COVERAGE_DIFF_FILE }}
          echo "${DETAIL_TABLE}"                           >> ${{ env.COVERAGE_DIFF_FILE }}
          echo "</details>"                                >> ${{ env.COVERAGE_DIFF_FILE }}

      - name: Console report
        if: steps.check_files.outputs.files_exists == 'true'
        run: cat ${{ env.COVERAGE_DIFF_FILE }}

      - name: Comment coverage diff file
        if: steps.check_files.outputs.files_exists == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: "${{ env.COVERAGE_DIFF_FILE }}"

  upload-base-coverage:
    if: github.ref == 'refs/heads/main'
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: "${{ env.PR_COVERAGE_FILE }}-${{ github.run_id }}"
          path: "${{ env.COVERAGE_DIR }}"
      - name: Rename base coverage file
        run: mv "${{ env.COVERAGE_DIR }}/lcov.info" "${{ env.MAIN_COVERAGE_FILE }}"
      - name: Upload coverage file
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.MAIN_COVERAGE_FILE }}"
          path: "${{ env.MAIN_COVERAGE_FILE }}"
