name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  COVERAGE_DIR: "target/coverage"
  PR_COVERAGE_FILE: "coverage-report.log"
  PR_COVERAGE_SUMMARY_FILE: "branch-coverage.log"
  COVERAGE_DIFF_FILE: "diff.log"
  MAIN_COVERAGE_FILE: "main-coverage.log"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download main coverage artifact
        run: gh run download -n ${{ env.MAIN_COVERAGE_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Prepare library

      # - uses: actions/setup-java@v3
      #   with:
      #     distribution: 'zulu'
      #     java-version: '8'
      # - uses: DeLaGuardo/setup-clojure@10.2
      #   with:
      #     lein: 2.9.8

      # # Coverage

      - name: Coverage report
        id: report-coverage
        run: |
          lein cloverage --no-colorize -o "${{ env.COVERAGE_DIR }}" > ${{ env.PR_COVERAGE_FILE }}

      - name: Diff coverage
        id: diff-coverage
        run: |
          cat ${{ env.PR_COVERAGE_FILE }} | sed -n '/Writing HTML report to/,$p' | sed '1,2d' > ${{ env.PR_COVERAGE_SUMMARY_FILE }}
          echo '```diff' > ${{ env.COVERAGE_DIFF_FILE }}
          diff --suppress-common-lines --color='never' ${{ env.PR_COVERAGE_SUMMARY_FILE }} ${{ env.MAIN_COVERAGE_FILE }} >> ${{ env.COVERAGE_DIFF_FILE }} || true
          echo '```' >> ${{ env.COVERAGE_DIFF_FILE }}
          cat ${{ env.COVERAGE_DIFF_FILE }}

      # # Post comment

      - name: Comment coverage
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: "${{ env.COVERAGE_DIFF_FILE }}"

      # # Archive coverage

      - name: Rename coverage file
        if: github.ref == 'refs/heads/main'
        run: mv "${{ env.PR_COVERAGE_SUMMARY_FILE }}" "${{ env.MAIN_COVERAGE_FILE }}"

      - name: Upload coverage
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.MAIN_COVERAGE_FILE }}"
          path: "${{ env.MAIN_COVERAGE_FILE }}"
