name: CI

on:
  workflow_call:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:

env:
  BUCKET: "blue-coverage-report"
  REGION: "ap-northeast-1"
  COVERAGE_DIR: "target/coverage"
  PR_COVERAGE_FILE: "coverage-report"
  MAIN_COVERAGE_FILE: "base-coverage-report"

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: DeLaGuardo/setup-clojure@10.2
        with:
          lein: 2.9.8
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

      - name: Calculate coverage of this branch
        run: |
          lein cloverage --lcov --no-colorize -o "${{ env.COVERAGE_DIR }}"

      - name: Upload html to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          HTML_DIR: "report-output"
        run: |
          npx lcov-viewer lcov -o "${{ env.HTML_DIR }}" "${{ env.COVERAGE_DIR }}/lcov.info"
          aws s3 cp --region ${{ env.REGION }} --recursive "${{ env.HTML_DIR }}/" "s3://${{ env.BUCKET }}/${{ github.run_id }}/"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.PR_COVERAGE_FILE }}-${{ github.run_id }}"
          path: "${{ env.COVERAGE_DIR }}/lcov.info"

  coverage-diff:
    if: github.ref != 'refs/heads/main'
    needs: [coverage]
    runs-on: ubuntu-latest
    env:
      COVERAGE_DIFF_FILE: "coverate-diff.log"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

      - uses: actions/download-artifact@v3
        with:
          name: "${{ env.PR_COVERAGE_FILE }}-${{ github.run_id }}"
          path: "${{ env.COVERAGE_DIR }}"

      - name: Download main coverage artifact
        run: gh run download -n ${{ env.MAIN_COVERAGE_FILE }} || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check coverage file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "${{ env.MAIN_COVERAGE_FILE }}, ${{ env.COVERAGE_DIR }}/lcov.info"

      - name: Create coverage diff comment
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          URL="[Full Coverage Report](https://${{ env.BUCKET }}.s3.${{ env.REGION }}.amazonaws.com/${{ github.run_id}}/index.html)"
          PR_TOTAL=$(npx lcov-total ${{ env.COVERAGE_DIR }}/lcov.info)
          BASE_TOTAL=$(npx lcov-total ${{ env.MAIN_COVERAGE_FILE }})
          DETAIL_TABLE=$(node main.js -b ${{ env.MAIN_COVERAGE_FILE }} -t ${{ env.COVERAGE_DIR }}/lcov.info --table --lines --icon)

          echo "# Change Coverage Report"                   > ${{ env.COVERAGE_DIFF_FILE }}
          echo "${URL}"                                    >> ${{ env.COVERAGE_DIFF_FILE }}
          echo ""                                          >> ${{ env.COVERAGE_DIFF_FILE }}
          echo "| PR          | Base branch   |"           >> ${{ env.COVERAGE_DIFF_FILE }}
          echo "| ---         | ---           |"           >> ${{ env.COVERAGE_DIFF_FILE }}
          echo "| ${PR_TOTAL} | ${BASE_TOTAL} |"           >> ${{ env.COVERAGE_DIFF_FILE }}
          echo ""                                          >> ${{ env.COVERAGE_DIFF_FILE }}
          echo "<details><summary>detail report</summary>" >> ${{ env.COVERAGE_DIFF_FILE }}
          echo "${DETAIL_TABLE}"                           >> ${{ env.COVERAGE_DIFF_FILE }}
          echo "</details>"                                >> ${{ env.COVERAGE_DIFF_FILE }}

      - name: Console report
        if: steps.check_files.outputs.files_exists == 'true'
        run: cat ${{ env.COVERAGE_DIFF_FILE }}

      - name: Comment coverage diff file
        if: steps.check_files.outputs.files_exists == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: "${{ env.COVERAGE_DIFF_FILE }}"

  upload-base-coverage:
    if: github.ref == 'refs/heads/main'
    needs: [coverage-diff]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: "${{ env.PR_COVERAGE_FILE }}-${{ github.run_id }}"
          path: "${{ env.COVERAGE_DIR }}"
      - name: Upload coverage file
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.MAIN_COVERAGE_FILE }}"
          path: "${{ env.COVERAGE_DIR }}/lcov.info"
